### ISSUE TITLE
Superfrog

### ISSUE THREAD

**Issue by SirVIeh** [krzykos/webaudio-mod-player#1]
Hej. Please add Superfrog music if possible. Thanks.

**Comment by krzykos** [comment]
Hi,
Sorry, but Superfrog music uses `The Player 4.x` format, which is not supported by the playback library.
Supported formats are listed in https://github.com/krzykos/webaudio-mod-player/blob/build/README.md

**Comment by krzykos** [comment]
Hey @SirVIeh !

In case you haven't noticed, please check out the new project: https://gamus.space/Amiga/Superfrog

Enjoy!
